package com.jewel.greendao.auto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jewel.model.cookery.RecipeDetail;
import com.jewel.model.cookery.RecipeInfo;

import com.jewel.greendao.auto.RecipeDetailDao;
import com.jewel.greendao.auto.RecipeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recipeDetailDaoConfig;
    private final DaoConfig recipeInfoDaoConfig;

    private final RecipeDetailDao recipeDetailDao;
    private final RecipeInfoDao recipeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recipeDetailDaoConfig = daoConfigMap.get(RecipeDetailDao.class).clone();
        recipeDetailDaoConfig.initIdentityScope(type);

        recipeInfoDaoConfig = daoConfigMap.get(RecipeInfoDao.class).clone();
        recipeInfoDaoConfig.initIdentityScope(type);

        recipeDetailDao = new RecipeDetailDao(recipeDetailDaoConfig, this);
        recipeInfoDao = new RecipeInfoDao(recipeInfoDaoConfig, this);

        registerDao(RecipeDetail.class, recipeDetailDao);
        registerDao(RecipeInfo.class, recipeInfoDao);
    }
    
    public void clear() {
        recipeDetailDaoConfig.clearIdentityScope();
        recipeInfoDaoConfig.clearIdentityScope();
    }

    public RecipeDetailDao getRecipeDetailDao() {
        return recipeDetailDao;
    }

    public RecipeInfoDao getRecipeInfoDao() {
        return recipeInfoDao;
    }

}
